name: hoophub
description: A community & nonprofit sports and hobby club management app.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management & architecture
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Firebase Core Packages
  firebase_core: ^3.5.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.2

  # (Optional but recommended for later use)
  firebase_messaging: ^15.0.1   # For push notifications
  firebase_storage: ^12.2.0     # For profile photo uploads
  flutter_application_1: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
