// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIItJIpmz-q6as8CDWHEVuQJGDYP9y3I',
    appId: '1:480868442303:web:1b8ec1fb5022dd02f1660a',
    messagingSenderId: '480868442303',
    projectId: 'data-layer-laude',
    authDomain: 'data-layer-laude.firebaseapp.com',
    storageBucket: 'data-layer-laude.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJaFrcSAd2WwuWbQgoVcC_NCt2hJshuQ4',
    appId: '1:480868442303:android:1f2ce81fb5c6a4bbf1660a',
    messagingSenderId: '480868442303',
    projectId: 'data-layer-laude',
    storageBucket: 'data-layer-laude.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JfbXxbIYE3mtuvzzFKulPDhPUTZJT7I',
    appId: '1:480868442303:ios:ac1a168c87e1dc35f1660a',
    messagingSenderId: '480868442303',
    projectId: 'data-layer-laude',
    storageBucket: 'data-layer-laude.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JfbXxbIYE3mtuvzzFKulPDhPUTZJT7I',
    appId: '1:480868442303:ios:ac1a168c87e1dc35f1660a',
    messagingSenderId: '480868442303',
    projectId: 'data-layer-laude',
    storageBucket: 'data-layer-laude.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbIItJIpmz-q6as8CDWHEVuQJGDYP9y3I',
    appId: '1:480868442303:web:d4812e69ae03c721f1660a',
    messagingSenderId: '480868442303',
    projectId: 'data-layer-laude',
    authDomain: 'data-layer-laude.firebaseapp.com',
    storageBucket: 'data-layer-laude.firebasestorage.app',
  );
}
